version: "3"
services:
  db-sql-postgres:
    image: "postgres:11.1"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: "db-sql"
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "SQL"
  db-sql-mysql:
    image: "mysql"
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: "SQL"
      MYSQL_DATABASE: "db-sql"
      MYSQL_USER: "admin"
      MYSQL_PASSWORD: "SQL"
    ports:
      - "3306:3306"